#if !canImport(ObjectiveC)
import XCTest

extension ByteOperationsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ByteOperationsTests = [
        ("testBitReader", testBitReader),
        ("testByteAndIntegerConvertion", testByteAndIntegerConvertion),
    ]
}

extension CollectionExtensionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CollectionExtensionTests = [
        ("testArrayLongestCommonPrefix", testArrayLongestCommonPrefix),
        ("testArrayLongestCommonSuffix", testArrayLongestCommonSuffix),
        ("testEmptyError", testEmptyError),
        ("testFindAllIndexes", testFindAllIndexes),
        ("testStringLongestCommonPrefixSuffix", testStringLongestCommonPrefixSuffix),
        ("testStringLongestCommonSuffix", testStringLongestCommonSuffix),
        ("testTwoArrayCommonPrefix", testTwoArrayCommonPrefix),
        ("testTwoArrayCommonSuffix", testTwoArrayCommonSuffix),
        ("testTwoStringCommonPrefix", testTwoStringCommonPrefix),
        ("testTwoStringCommonSuffix", testTwoStringCommonSuffix),
    ]
}

extension KwiftExtensionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KwiftExtensionTests = [
        ("testAutoreleasepool", testAutoreleasepool),
        ("testSafeFilename", testSafeFilename),
        ("testSortKeyPath", testSortKeyPath),
        ("testStringCharacterPartialSubscript", testStringCharacterPartialSubscript),
        ("testStringSubscript", testStringSubscript),
    ]
}

extension KwiftUtilityTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KwiftUtilityTests = [
        ("testQueue", testQueue),
        ("testResolutionParse", testResolutionParse),
    ]
}

extension OptionalExtensionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OptionalExtensionTests = [
        ("testUnwrap", testUnwrap),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ByteOperationsTests.__allTests__ByteOperationsTests),
        testCase(CollectionExtensionTests.__allTests__CollectionExtensionTests),
        testCase(KwiftExtensionTests.__allTests__KwiftExtensionTests),
        testCase(KwiftUtilityTests.__allTests__KwiftUtilityTests),
        testCase(OptionalExtensionTests.__allTests__OptionalExtensionTests),
    ]
}
#endif
