#if !canImport(ObjectiveC)
import XCTest

extension KwiftExtensionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KwiftExtensionTests = [
        ("testCheckEmptyCollection", testCheckEmptyCollection),
        ("testLongestCommonPrefix", testLongestCommonPrefix),
        ("testLongestCommonSuffix", testLongestCommonSuffix),
        ("testSafeFilename", testSafeFilename),
        ("testSortKeyPath", testSortKeyPath),
        ("testStringCharacterPartialSubscript", testStringCharacterPartialSubscript),
        ("testStringSubscript", testStringSubscript),
        ("testUnwrapOptional", testUnwrapOptional),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(KwiftExtensionTests.__allTests__KwiftExtensionTests),
    ]
}
#endif
