#if !canImport(ObjectiveC)
import XCTest

extension SwiftEnhancementTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftEnhancementTests = [
        ("testStringSubscript", testStringSubscript),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftEnhancementTests.__allTests__SwiftEnhancementTests),
    ]
}
#endif
