#if !canImport(ObjectiveC)
import XCTest

extension KwiftUtilityTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KwiftUtilityTests = [
        ("testByteOperations", testByteOperations),
        ("testQueue", testQueue),
        ("testResolutionParse", testResolutionParse),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(KwiftUtilityTests.__allTests__KwiftUtilityTests),
    ]
}
#endif
