#if !canImport(ObjectiveC)
import XCTest

extension ExecutableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExecutableTests = [
        ("testExecutableCatch", testExecutableCatch),
        ("testExecutableCatchLargeOutputPerformance", testExecutableCatchLargeOutputPerformance),
        ("testExecutableCatchPerformance", testExecutableCatchPerformance),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ExecutableTests.__allTests__ExecutableTests),
    ]
}
#endif
