#if !canImport(ObjectiveC)
import XCTest

extension KwiftExtensionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KwiftExtensionTests = [
        ("testStringSubscript", testStringSubscript),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(KwiftExtensionTests.__allTests__SwiftEnhancementTests),
    ]
}
#endif
