name: CI

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
        swift: ["5.1.1", "5.0.3"]
    steps:
    - uses: actions/checkout@v1
    - uses: fwal/setup-swift@master
      with:
        swift-version: ${{ matrix.swift }}
    - name: Get swift version
      run: swift --version
    - name: Debug build
      run: swift build
    - name: Test
      run: swift test
    - name: Release build
      run: swift build -c release
