name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
        - swift:nightly-focal
        - swift:5.3-focal
        - swift:5.3-centos7
        - swift:5.3-centos8
    container:
      image: ${{ matrix.images }}
    steps:
    - uses: actions/checkout@v2
    - name: Swift version
      run: swift --version
    - name: Build Debug
      run: swift build
    - name: Build Release
      run: swift build -c release
    - name: Run tests
      run: swift test -v
